spring.application.name=idempotency-gateway
server.port=8080

idempotency.key.ttl-hours=24
idempotency.processing-delay-ms=2000
idempotency.purge-interval-ms=3600000

spring.datasource.url=jdbc:mysql://localhost:3308/idempotency_gateway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:Prince Jocos9}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
